In [1]:
exec(open("./funcs/tool_funcs.py").read())


In [2]:
# random.seed(200)
# np.random.seed(200)

In [3]:
N = 100


X_distance_matrix = create_distance_matrix(N)

In [4]:
 
 
np.savetxt("./data/X_distance_matrix.csv", X_distance_matrix, delimiter=",", fmt="%f") 


In [5]:
X_distance_matrix[1,:10]

array([494.,   0., 358., 491., 842., 116., 593., 525., 960.,  15.])

In [6]:

X_distance_matrix1 = np.loadtxt("./data/X_distance_matrix.csv", delimiter=",")
 


In [7]:
X_distance_matrix[1,:10]

array([494.,   0., 358., 491., 842., 116., 593., 525., 960.,  15.])

In [8]:
X_distance_matrix1[1,:10]

array([494.,   0., 358., 491., 842., 116., 593., 525., 960.,  15.])

In [9]:
X_distance_matrix1.shape

(100, 100)

In [10]:
X_distance_matrix1

array([[  0., 123.,  73., ..., 831., 869., 702.],
       [494.,   0., 358., ..., 234., 571.,  30.],
       [126.,  43.,   0., ...,  56.,  59., 383.],
       ...,
       [235., 347., 113., ...,   0., 507., 350.],
       [652., 417., 377., ..., 811.,   0., 232.],
       [179., 884., 615., ..., 745., 304.,   0.]])