In [1]:


#Algorithm 1 works when the graph has negative weights. 
#However, it does not work when the graph has negative circles. 
#The Floyd-Warshall algorithm does not either.


In [2]:
exec(open("./funcs/tool_funcs.py").read())


In [3]:
def shortest_path_n_to_r(distance_matrix, shortest_path_matrix, n, r):
    max_jump_list = []
    for t in range(n):
        m_jump =  distance_matrix[n,t] + shortest_path_matrix[t,r]
        max_jump_list.append(m_jump)
    return np.min(max_jump_list)

def shortest_path_r_to_n(distance_matrix, shortest_path_matrix, n, r):
    max_jump_list = []
    for t in range(n):
        m_jump =  shortest_path_matrix[r,t] + distance_matrix[t, n] 
        max_jump_list.append(m_jump)
    return np.min(max_jump_list)

     
def cal_n_shortest_path(distance_matrix, shortest_path_matrix, n):
    for r in range(n):
        shortest_path_matrix[n,r] = shortest_path_n_to_r(distance_matrix, shortest_path_matrix, n, r)
        shortest_path_matrix[r,n] = shortest_path_r_to_n(distance_matrix, shortest_path_matrix, n, r)
        
    for i in range(n):        
        for j in range(n):
            if i < j:
                shortest_path_matrix[i,j] =  update_shortest_path_ij(distance_matrix, shortest_path_matrix, n, i, j)
                shortest_path_matrix[j,i] =  update_shortest_path_ij(distance_matrix, shortest_path_matrix, n, j, i)
                
def update_shortest_path_ij(distance_matrix, shortest_path_matrix, n, i, j):
    m1 = shortest_path_matrix[i,j]
    m2 =  shortest_path_matrix[i,n] + shortest_path_matrix[n,j] 
    return np.min((m1,m2))

def cal_shortest_path_matrix_algo_1_python(distance_matrix):
    
  
    N = len(distance_matrix)
   
    shortest_path_matrix = np.zeros((N,N))

    shortest_path_matrix[0,1] = distance_matrix[0,1]
    shortest_path_matrix[1,0] = distance_matrix[1,0]
 
    for kk in range(2,N):
        cal_n_shortest_path(distance_matrix, shortest_path_matrix, kk)
    return shortest_path_matrix

In [4]:
N = 10
 
dist_matrix = create_distance_matrix(N)

dist_matrix.shape

(10, 10)

In [5]:
dist_matrix

array([[  0., 617., 159.,   1., 117., 214., 349., 632., 573., 401.],
       [919.,   0., 147., 902., 802., 963.,  88., 340.,  63., 174.],
       [771., 329.,   0., 575.,  62., 518., 842., 229., 566., 504.],
       [ 49., 896., 101.,   0., 651., 849., 504.,  25., 639., 876.],
       [714., 197., 428., 639.,   0., 132., 174., 543., 965., 472.],
       [481., 717., 552., 787., 291.,   0.,  85., 513., 169., 984.],
       [789., 235., 348., 859., 395.,  44.,   0., 221., 233., 218.],
       [164., 103., 622., 621., 284.,  38., 625.,   0., 951.,   4.],
       [620., 153., 153., 383., 106., 878., 792., 913.,   0.,  58.],
       [730., 384., 244., 293., 441., 457., 447., 697., 360.,   0.]])

In [6]:
dist_matrix[2,3] = -2

dist_matrix[3,9] = -3

dist_matrix[1,6] = -8
dist_matrix

array([[  0., 617., 159.,   1., 117., 214., 349., 632., 573., 401.],
       [919.,   0., 147., 902., 802., 963.,  -8., 340.,  63., 174.],
       [771., 329.,   0.,  -2.,  62., 518., 842., 229., 566., 504.],
       [ 49., 896., 101.,   0., 651., 849., 504.,  25., 639.,  -3.],
       [714., 197., 428., 639.,   0., 132., 174., 543., 965., 472.],
       [481., 717., 552., 787., 291.,   0.,  85., 513., 169., 984.],
       [789., 235., 348., 859., 395.,  44.,   0., 221., 233., 218.],
       [164., 103., 622., 621., 284.,  38., 625.,   0., 951.,   4.],
       [620., 153., 153., 383., 106., 878., 792., 913.,   0.,  58.],
       [730., 384., 244., 293., 441., 457., 447., 697., 360.,   0.]])

In [7]:


shortest_path_matrix_floyd_warshall = floyd_warshall(dist_matrix)



In [8]:


shortest_path_matrix_algo_1 = cal_shortest_path_matrix_algo_1_python(dist_matrix)


In [9]:
print(np.allclose(shortest_path_matrix_algo_1, shortest_path_matrix_floyd_warshall)) 
print(np.sum(np.abs(shortest_path_matrix_algo_1 - shortest_path_matrix_floyd_warshall))) 


True
0.0


In [10]:
shortest_path_matrix_algo_1

array([[  0., 129., 102.,   1., 117.,  64., 121.,  26., 192.,  -2.],
       [194.,   0., 147., 145., 169.,  36.,  -8., 170.,  63., 121.],
       [ 47., 126.,   0.,  -2.,  62.,  61., 118.,  23., 189.,  -5.],
       [ 49., 128., 101.,   0., 163.,  63., 120.,  25., 191.,  -3.],
       [391., 197., 344., 342.,   0., 132., 174., 367., 260., 318.],
       [369., 320., 322., 320., 275.,   0.,  85., 306., 169., 227.],
       [385., 235., 348., 346., 319.,  44.,   0., 221., 213., 218.],
       [164., 103., 248., 165., 272.,  38.,  95.,   0., 166.,   4.],
       [200., 153., 153., 151., 106., 189., 145., 176.,   0.,  58.],
       [291., 370., 244., 242., 306., 305., 362., 267., 360.,   0.]])

In [11]:
shortest_path_matrix_floyd_warshall

array([[  0., 129., 102.,   1., 117.,  64., 121.,  26., 192.,  -2.],
       [194.,   0., 147., 145., 169.,  36.,  -8., 170.,  63., 121.],
       [ 47., 126.,   0.,  -2.,  62.,  61., 118.,  23., 189.,  -5.],
       [ 49., 128., 101.,   0., 163.,  63., 120.,  25., 191.,  -3.],
       [391., 197., 344., 342.,   0., 132., 174., 367., 260., 318.],
       [369., 320., 322., 320., 275.,   0.,  85., 306., 169., 227.],
       [385., 235., 348., 346., 319.,  44.,   0., 221., 213., 218.],
       [164., 103., 248., 165., 272.,  38.,  95.,   0., 166.,   4.],
       [200., 153., 153., 151., 106., 189., 145., 176.,   0.,  58.],
       [291., 370., 244., 242., 306., 305., 362., 267., 360.,   0.]])